### ISSUE TITLE
A question about sequence types

### ISSUE THREAD

**Issue by ggl2151** [azureycy/dbAPIS#1]
Hello Author,  I want to ask a question. I noticed that the input sequences for diamond need to be amino acid sequences. However, my whole genome sequences are nucleotide sequences.

I would like to ask if I need to first find a tool to translate my genomic sequences into amino acid sequences, or if there is another way I can use dbAPIS directly with nucleotide sequences?

I would greatly appreciate any suggestions you may have on the proper workflow for using dbAPIS with whole genome nucleotide sequences. Thank you very much for your time and for providing this useful tool to the research community.

**Comment by azureycy** [comment]
> Hello Author, I want to ask a question. I noticed that the input sequences for diamond need to be amino acid sequences. However, my whole genome sequences are nucleotide sequences.
> 
> I would like to ask if I need to first find a tool to translate my genomic sequences into amino acid sequences, or if there is another way I can use dbAPIS directly with nucleotide sequences?
> 
> I would greatly appreciate any suggestions you may have on the proper workflow for using dbAPIS with whole genome nucleotide sequences. Thank you very much for your time and for providing this useful tool to the research community.

Hello, thanks for asking. Yes, you need to translate the nucleotide sequence to amino acid sequence. So far dbAPIS only accepts amino acid sequence as input, we plan to allow nucleotide sequence submission in the future update.

**Comment by ggl2151** [comment]
Thank you very much for the confirmation. Also, I look forward to the future update that would allow direct nucleotide sequence submissions.
