### ISSUE TITLE
A question about hmmsan

### ISSUE THREAD

**Issue by ggl2151** [azureycy/dbAPIS#2]
Hello, sorry to bother you again. When I used hmmscan to predict genes in my strain genome (all contigs were translated into amino acid sequences, see genome file contents in Attachment 1)
![Attachment1](https://github.com/azureycy/dbAPIS/assets/74592616/96fb0f65-88c4-4f69-9ccc-b4d3b60d93cc)
, I found that hmmscan only made predictions on my chromosomal contig sequences, and did not make predictions on some plasmid contigs that followed (as shown in Attachment 2)
![Attachment2](https://github.com/azureycy/dbAPIS/assets/74592616/cb906b85-c40f-43a5-a444-3ad201d70337)
. However, when I deleted the first chromosomal sequence from the genome file, hmmscan would then predict genes for all the plasmid contigs (as shown in Attachment 3)
![Attachment3](https://github.com/azureycy/dbAPIS/assets/74592616/bbb68047-6e69-42be-8b4c-d4d36669b6d6)
. I would like to ask if hmmscan supports prediction for WGS data, or if hmmscan can only predict genes for a single amino acid sequence. Thank you.

**Comment by azureycy** [comment]
Hi @ggl2151 ,

hmmscan can be used to analyze either a single amino acid sequence or multiple sequences. It seems in your Attachment 2 there is a core dumped issue leading to process aborted. There are many "*" in your translated aa sequences, it's recommended to identify the protein-coding regions in the genomic DNA first then translate these regions into aa sequences.
